import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { logger } from "./logger.js";
import type { PipelineResult } from "./types.js";

const execFileAsync = promisify(execFile);

// GitHub PR comment body limit
const MAX_BODY_LENGTH = 60_000;

interface ReviewIssue {
  severity: string;
  category: string;
  file: string;
  line?: number;
  description: string;
  suggestion?: string;
  remediation?: string;
  impact?: string;
  cwe?: string;
}

interface ReviewReport {
  verdict: string;
  summary: string;
  issues?: ReviewIssue[];
  stats?: Record<string, unknown>;
  risk_level?: string;
}

/**
 * Try to parse a structured review JSON from the agent output.
 * The output may contain markdown or text around the JSON block.
 */
function parseReviewReport(raw: string): ReviewReport | undefined {
  // Try direct JSON parse first
  try {
    return JSON.parse(raw) as ReviewReport;
  } catch {
    // noop
  }

  // Try to find a JSON block in markdown code fences
  const fenceMatch = raw.match(/```(?:json)?\s*\n([\s\S]*?)\n```/);
  if (fenceMatch) {
    try {
      return JSON.parse(fenceMatch[1]) as ReviewReport;
    } catch {
      // noop
    }
  }

  // Try to find the outermost JSON object
  const braceStart = raw.indexOf("{");
  const braceEnd = raw.lastIndexOf("}");
  if (braceStart !== -1 && braceEnd > braceStart) {
    try {
      return JSON.parse(raw.slice(braceStart, braceEnd + 1)) as ReviewReport;
    } catch {
      // noop
    }
  }

  return undefined;
}

function severityEmoji(severity: string): string {
  switch (severity.toUpperCase()) {
    case "CRITICAL":
      return "🔴";
    case "HIGH":
      return "🟠";
    case "WARNING":
    case "MEDIUM":
      return "🟡";
    case "SUGGESTION":
    case "LOW":
      return "🔵";
    default:
      return "⚪";
  }
}

function formatIssuesTable(issues: ReviewIssue[]): string {
  if (issues.length === 0) return "";

  const rows = issues.map((issue) => {
    const location = issue.line ? `${issue.file}:${issue.line}` : issue.file;
    const emoji = severityEmoji(issue.severity);
    return `| ${emoji} ${issue.severity} | ${issue.category} | \`${location}\` | ${issue.description} |`;
  });

  return [
    "",
    "| Severity | Category | Location | Description |",
    "|----------|----------|----------|-------------|",
    ...rows,
    "",
  ].join("\n");
}

function formatMarkdownComment(report: ReviewReport): string {
  const verdictEmoji = report.verdict === "APPROVED" ? "✅" : "⚠️";
  const lines: string[] = [];

  lines.push(`## ${verdictEmoji} Voltaire Review — ${report.verdict}`);
  lines.push("");
  lines.push(report.summary);

  if (report.risk_level) {
    lines.push("");
    lines.push(`**Risk level**: ${report.risk_level}`);
  }

  if (report.issues && report.issues.length > 0) {
    lines.push("");
    lines.push("### Issues");
    lines.push(formatIssuesTable(report.issues));
  }

  if (report.stats) {
    const parts = Object.entries(report.stats)
      .map(([key, val]) => `**${key.replace(/_/g, " ")}**: ${String(val)}`)
      .join(" · ");
    lines.push(`> ${parts}`);
  }

  lines.push("");
  lines.push("---");
  lines.push("_Generated by Voltaire review pipeline_");

  return lines.join("\n");
}

function formatFallbackComment(summary: string): string {
  return [
    "## 🔍 Voltaire Review",
    "",
    summary,
    "",
    "---",
    "_Generated by Voltaire review pipeline_",
  ].join("\n");
}

/**
 * Post review findings as a comment on the GitHub PR.
 * Non-blocking — errors are logged but never thrown.
 */
export async function postReviewComment(
  result: PipelineResult,
): Promise<void> {
  if (!result.prNumber || !result.repository) {
    logger.warn("postReviewComment: missing prNumber or repository, skipping");
    return;
  }

  const repo = result.repository.replace("github.com/", "");
  const summary = result.summary ?? "";

  if (!summary.trim()) {
    logger.warn(`postReviewComment: empty summary for PR #${String(result.prNumber)}, skipping`);
    return;
  }

  const report = parseReviewReport(summary);
  let body = report
    ? formatMarkdownComment(report)
    : formatFallbackComment(summary);

  // Truncate if necessary
  if (body.length > MAX_BODY_LENGTH) {
    body = body.slice(0, MAX_BODY_LENGTH - 100) + "\n\n_(truncated)_";
  }

  try {
    await execFileAsync(
      "gh",
      ["pr", "comment", String(result.prNumber), "--repo", repo, "--body", body],
      { timeout: 30_000 },
    );
    logger.info(`Posted review comment on PR #${String(result.prNumber)} (${repo})`);
  } catch (error) {
    logger.warn(`Failed to post review comment on PR #${String(result.prNumber)}`, error);
  }
}
