.TH NEO-VERSION 1 "March 2026" "neo 0.1.0" "Neo CLI Manual"
.SH NAME
neo-version \- display the current neo version
.SH SYNOPSIS
.B neo version
.SH DESCRIPTION
.B neo version
displays the version of the neo CLI that is currently installed.
.PP
The version is read from the @neotx/cli package.json file.
.SH OUTPUT
.PP
.RS
.nf
neo v0.1.0
.fi
.RE
.SH EXAMPLES
Display version:
.PP
.RS
.nf
neo version
.fi
.RE
.SH EXIT STATUS
.TP
.B 0
Success.
.SH SEE ALSO
.BR neo (1)
